### PR TITLE
Added support for JSON data type and additional object change tracking.

### PR DESCRIPTION
**Pull request by gbenvenuti**

### CODE REVIEW

**Comment by mkopinsky** [comment]
Nice work. Even if @ozsynergy doesn't merge this here, we might be interested in merging this work into https://github.com/waytohealth/doctrine1 (if that's OK with you).

One thing that is missing (in my mind) is tests. I don't have time right now to write some, but if you did, I would definitely be interested in merging this into my repo.

**Comment by ozsynergy** [comment]
I would welcome a PR with added tests @mkopinsky

**Comment by gbenvenuti** [comment]
Hi @mkopinsky,
This was just a quick patch for a project @ozsynergy and I work on together, didn't realise there was any downstream users :) 

You're right it should have tests but don't have time atm.  It is working in Postgres which is our only use for this.

**Comment by mkopinsky** [comment]
We're not currently depending on this repo, but we were for a while. We now are using a version forked from zhttps://github.com/lexpress/doctrine1.

If I get around to writing tests, I definitely will contribute them back here as well.

**Pull request merged**
